### ISSUE TITLE
Wrong output focus

### ISSUE THREAD

**Issue by tmfink** [tmfink/i3-wk-switch#1]
When switching to a a new workspace by calling the script from a terminal, the correct output has focus.

When using keys bound to the script, the wrong output has focus.

**Comment by abondis** [comment]
same problem here

**Comment by trrichard** [comment]
I also have the same problem, here's what I've found out so far:

When the final "focus output" command is run i3's logs indicate that there won't be a switch because the workspace is "already there"

workspace.c:_workspace_show:355 - Not switching, already there.

(You can turn on and dump the logs with i3-msg 'debuglog off; shmlog off; reload' and i3-dump-log respectively.)

When I run the command from command line this does work. And I am able to get the i3-wk-switch script to work from a hotkey by adding a 1/4 second delay into the script before refocusing...

This points to a concurrency problem in i3 where the commands from i3-wk-switcher are registering but not actually having an effect for some small time. 

I think to fix this we would probably need to adjust i3's behaviour, but to hack around it, the quarter second (or more?) delay should work  for most people.

If you get a chance, try adding a little delay to the script and see if that works for you.

I'm going to file a merge request for my branch.

**Comment by trrichard** [comment]
Also this could totally be fixed in the new version of i3. If either of you could let me know I would appreciate it.

 I'm using apt-get package from ubuntu 14.04.

**Comment by abondis** [comment]
sorry, I won't be able to test, I switched back to spectrwm and removed all my i3 setup/configuration.

**Comment by abondis** [comment]
I tried it today, and it seems fine. Thanks a lot.
